development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: pictour
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  port: 5432
  reconnect: false
  username: postgres
  password: password
  database: pictour        
  pool: 5
  host: localhost